### ISSUE TITLE
Running user code

### ISSUE THREAD

**Issue by danbulant** [fengari-lua/fengari#186]
Is there a way to securely run user code? I have never used lua C API (or fengari), and looking through the docs didn't give me much of an idea about what should I do.

I would like to run the code in a sandbox in node (I'll run it in a worker), and would like to limit the access to node objects (if possible, I would like to provide custom functions/objects to use as context). From docs, I thought I could just create state (`fengari.lauxlib.luaL_newstate()`), open default libs (`fengari.lualib.luaL_openlibs(L)`), set handler for panic (`fengari.lua.lua_atpanic(L, handler)`) and run it with `fengari.lauxlib.luaL_dostring(L, code)`. But this didn't yield any results, and in fact, the last one should return boolean (true = failed, false = succeeded) but instead returned a number (-1 when I passed `print "Hello world"` as code). Also, I couldn't find a way to pass objects/functions to use (custom handler for print, for example) nor how to capture output (it didn't write anything).

**Comment by DHBrett** [comment]
@danbulant I'm pretty new to fengari as well, but I've got a similar use-case to what you're describing and I've found a couple other things that seem useful to lock things down.

First, instead of using `luaL_openlibs` from [here](https://github.com/fengari-lua/fengari/blob/1cd5b00d25478b35deba1329d95a342062c51d4c/src/linit.js) as I've seen in some samples, I pulled out just the libraries I wanted (base, coroutine, table, string, and math) and imported them like this **in js**:
```
    const luaLib = fengari.lualib;
    const loadedLibs = {};
    loadedLibs["_G"] = luaLib.luaopen_base;
    loadedLibs[luaLib.LUA_COLIBNAME] = luaLib.luaopen_coroutine;
    loadedLibs[luaLib.LUA_TABLIBNAME] = luaLib.luaopen_table;
    loadedLibs[luaLib.LUA_STRLIBNAME] = luaLib.luaopen_string;
    loadedLibs[luaLib.LUA_MATHLIBNAME] = luaLib.luaopen_math;

    for (let lib in loadedLibs) {
      fengari.lauxlib.luaL_requiref(
        L,
        fengari.to_luastring(lib),
        loadedLibs[lib],
        1
      );
      fengari.lua.lua_pop(L, 1);
    }
```

Then once I was ready to run the untrusted code, I first nil-ed out all the globals that I didn't want **in Lua**:
```
      collectgarbage = nil
      dofile = nil
      getmetatable = nil
      load = nil
      loadfile = nil
      setmetatable = nil
      pcall = nil
      rawget = nil
      rawlen = nil
      rawequal = nil
      rawset = nil
      xpcall = nil
```
The goal with this is just to prevent the code from getting access to anything it shouldn't (and I certainly can't guarantee it will be enough to do that!), but you should also consider how you're going to keep resource usage reasonable. You don't want untrusted code to take all the CPU or memory and crash your backend.

I'd love to get an actual expert's opinion, @daurnimator or someone else with more experience with the library.

---------------------------------------

As for your question about how to print to the console, I ended up replacing the default print function in my lua state and then holding the results in react state:
```
  public static addPrintHandler = (
    L: LuaState,
    callback: (printed: string) => void
  ) => {
    const func = (L: LuaState) => {
      const printed = interop.tojs(L, 1);
      callback(printed);

      return 0;
    };

    LuaFunctions.defineGlobalFunction(L, func, "print");
  };

  static defineGlobalFunction = (
    L: LuaState,
    fn: (L: LuaState) => any,
    name: string
  ) => {
    // define global fn call
    fengari.lua.lua_pushjsfunction(L, fn);
    fengari.lua.lua_setglobal(L, fengari.to_luastring(name));
  };
```
which I then use like this:
```
    LuaFunctions.addPrintHandler(L, printed => {
      if (typeof printed !== "string") {
        try {
          printed = JSON.stringify(printed);
        } catch {
          printed = "Circular object";
        }
      }

      console.log(printed);
      // Add new string to state
      ...
    });
```

Hopefully that's helpful for you, if not, we'll just have to hope [Cunningham's Law](https://meta.wikimedia.org/wiki/Cunningham%27s_Law) comes through

**Comment by pineapplemachine** [comment]
Here's a good resource related to running untrusted Lua code: https://roblox.github.io/luau/sandbox.html

**Comment by mxdpeep** [comment]
it looks like this repo is abandoned

**Comment by daurnimator** [comment]
This is not a well formed question that I feel like walking through answering.

> Is there a way to securely run user code? I have never used lua C API (or fengari), and looking through the docs didn't give me much of an idea about what should I do.

Sandboxing is a complex topic that comes up regularly on the lua mailing list. Try http://lua-users.org/wiki/SandBoxes for a launcing off point



> the last one should return boolean (true = failed, false = succeeded) but instead returned a number

Why do you expect it to return a boolean? It returns a lua status code. see https://www.lua.org/manual/5.3/manual.html#lua_pcall 



> it looks like this repo is abandoned

Not at all; but us authors have limited time to work on fengari
