### ISSUE TITLE
print behavior

### ISSUE THREAD

**Issue by TymurGubayev** [fengari-lua/fengari#67]
Minor issue (or maybe not one at all)

executing `print(1,2)` on http://fengari.io/ produces 2 lines, while on https://www.lua.org/cgi-bin/demo a single one (the values are separated with TAB).

**Comment by giann** [comment]
Your get 2 lines on the web repl but not with [the cli](https://github.com/fengari-lua/fengari-node-cli)

**Comment by daurnimator** [comment]
Please re-file against fengari-web-cli, this behaviour is related to the
behaviour of our replacement print function for the web repl

On 25 Jul 2017 7:19 PM, "TymurGubayev" <notifications@github.com> wrote:

Minor issue (or maybe not one at all)

executing print(1,2) on http://fengari.io/ produces 2 lines, while on
https://www.lua.org/cgi-bin/demo a single one (the values are separated
with TAB).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fengari-lua/fengari/issues/67>, or mute the thread

**Comment by RyanSquared** [comment]
https://github.com/fengari-lua/fengari-web-cli/issues/7
