### ISSUE TITLE
Use Function.displayName and/or Function.name for JS functions in tracebacks

### ISSUE THREAD

**Issue by daurnimator** [fengari-lua/fengari#79]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/displayName

> It is usually preferred by consoles and profilers over func.name to display the name of a function.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name

**Comment by daurnimator** [comment]
See https://github.com/fengari-lua/fengari/issues/86#issuecomment-332512046

Firefox didn't seem to use the field.

For chrome I had to use:
```js
Object.defineProperty(func, "name", {
    enumerable: false,
    writable: false,
    configurable: true,
    value: "my_function_name"
});
```

**Comment by daurnimator** [comment]
I don't think this is useful with minification being as common as it is.

**Comment by Benaiah** [comment]
I've been trying to figure out how to get `displayName` set so that React function components (which are just functions that return created React elements) will show up with useful names in the React Developer Tools extension. However, trying to set a property on a function in Lua in Fengari causes an error (matching Lua semantics), but creating a JS function that sets the `displayName` and calling it on a Lua function in Fengari simply fails to take effect. Is there any potential workaround to set the property on the object passed into JS, even manually?

**Comment by daurnimator** [comment]
>  Is there any potential workaround to set the property on the object passed into JS, even manually?

See https://github.com/fengari-lua/fengari-interop#createproxyx-type
> The proxy supports configuring traps by setting them as metamethods on your object.

I think setting a `"get"` trap on your function will work.
